### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by gczuczy** [JereKuusela/valheim-ore_support#1]
This mod seemed appealing for getting rocks from the mountains, but nothing appears or happens, not even if we try to bind it to any key and spamming the bound key.

**Comment by JereKuusela** [comment]
Hey, the mod is intended to activate only after certain amount of parts exist in the deposit. You can configure this by increasing max boxes and max parts values.

I guess on the next version I will make it always active since you are not the first one wondering is it working.

**Comment by gczuczy** [comment]
It activated three times. We've dug out 6-7 rocks grown along, practically disassembling half the mountain side. Maybe rocks are bigger and the lower threshold is way too low. The problem is we don't quite know what to knock out to reach the "certain number" to activate.

I will check the config next time.

**Comment by JereKuusela** [comment]
Yeah, it's probably bit too low for those bigger rocks. Default values don't make that much sense anyways since you can now toggle it on/off more easily.

**Comment by JereKuusela** [comment]
Added a new version 1.4.0 that has better default values. After updating you can delete the config file to get new default values or jsut editr the config by yourself.

**Comment by gczuczy** [comment]
> Yeah, it's probably bit too low for those bigger rocks. Default values don't make that much sense anyways since you can now toggle it on/off more easily.

Now that was weird. I've bound it to capslock, and repeatedly tapping the key didn't do anything. _However_ when the bounding boxes appeared 3 times, I indeed could toggle the mod on and off with the key. But by default, it was doing totally nothing, like not even detecting there's a half square kilometer rock hanging in the air above my head.
